### PR TITLE
Dateispeicher Browser

### PR DESCRIPTION
**Pull request by alessioC42**
Add a browser for the "Dateispeicher" Applet based on the existing Parser.

- [x] basic functionality
- [x] error handling
- [x] file search
- [x] mb show if a file is already in storage (problems with different files and same url?)

@CodeSpoof Do you know if a modified file has a different download URL when it has the same remote path and filename? Also does your school have the search in files feature? Is it just a different AJAX request lanis can disable from school to school like the replacements.

### CODE REVIEW

**Comment by CodeSpoof** [comment]
Files can only be renamed, not edited. Thus the id will change when reuploading a modified version. The SPH is patrtially inconsistent when it comes to keeping file-IDs when renaming.

**Comment by CodeSpoof** [comment]
Search will be tested tomorrow.

**Comment by alessioC42** [comment]
> Search will be tested tomorrow.

I've implemented the endpoint on the branch. You can test it right there

**Comment by alessioC42** [comment]
https://github.com/alessioC42/lanis-mobile/assets/84250128/c6bb1d57-a93f-4feb-9432-000bdcd3508b

**Review by CodeSpoof — APPROVED** [review]

**Pull request merged**
