### PR TITLE
Proxy fix

### LINKED ISSUE #221: App doesn't work in School Network with Proxy
Steps to reproduce:

1. Connect to School Network (Ethernet or WiFi)  and setup School Proxy (in my case `SchuleGYM` of the Georg-Christoph-Lichtenberg Schule Kassel
2. Try open the App while conneted to this School Network (Android or iOS)
3. Get Error: No Internet connection!

If  a Port or Domains is blocked by the Proxy i can may resolve the issue by unlocking it. But for this i need to know the specific Domain, Port or Protocol or if the App supports Proxy at all

Tested on Android and iOS

### PR DESCRIPTION
**Pull request by alessioC42**
It appears that dio does not use the default system proxy when creating requests. This modification uses the system proxy if available.

Should fix #221 

waiting for testing from @Rajala1404 before merge

### CODE REVIEW

**Comment by Rajala1404** [comment]
Good, I will test this next Monday

**Comment by Rajala1404** [comment]
I'm happy to say that it works, but the Login Page can't fetch the Schools, i think you may need to implement the DIO at there too (I don't know what file is responsible for this otherwise i would make a quick fix.

**Comment by Rajala1404** [comment]
So i tried it but on the Login Page the Schools don't load and i tested to pre-login and the open the App but realized that i used my Mobile Data so i will try to just use School WiFi. But the School WiFi currently refuses to connect so i Edit this comment as soon i tried it with Pre-Login

**Comment by alessioC42** [comment]
Okay, I have an other theory. I will try to implement an fix asap

**Comment by alessioC42** [comment]
Could you test it now? I have set up proxyman to ensure, that it pipes through the proxy, but I am not able to test it in your school.

**Comment by Rajala1404** [comment]
Ok, I try it tomorrow in School

**Comment by Rajala1404** [comment]
So i tried it, it detects the right Proxy with the Right Port but it still doesn't work. But i did not get the No Network Error Message. I got an Critical Error with an UnknownException: Unbekannter Fehler! The logs don't print any Error at the Time that Error occurs. I attach an Screenshot from my Phone. I may try to add the Logging, i think that the log will be useless because it printed nothing regarding any Error at the Failure Time.

**Comment by alessioC42** [comment]
At this point I have no idea, why you are not able to connect. You already wrote the basic Proxy information in #221 and it is a wired server! First of all I do not really understand, why the proxy is accessible via the Internet and even then there are some restrictions set up. Apparently it blocks ping requests, but `nmap` still is able to find some services.
```
>>>>>>>>>>>>>>> ping edu.silk-it.de
PING edu.silk-it.de (10.100.0.11) 56(84) bytes of data.
^C
--- edu.silk-it.de ping statistics ---
5 packets transmitted, 0 received, 100% packet loss, time 4060ms

>>>>>>>>>>>>>>> nmap edu.silk-it.de -Pn -p 8080
Starting Nmap 7.95 ( https://nmap.org ) at 2024-06-04 16:17 CEST
Nmap scan report for edu.silk-it.de (10.100.0.11)
Host is up.
Other addresses for edu.silk-it.de (not scanned): 10.100.0.12 10.100.0.10

PORT     STATE    SERVICE
8080/tcp filtered http-proxy

Nmap done: 1 IP address (1 host up) scanned in 2.04 seconds
```
I think that none of my requests succeed, due to the `filtered` state of the port. I am at a point, where I am not able to reproduce the error in any way. All requests are piped through my proxy (with and without filters) and succeed. May some access to the network (or proxy) via vpn or something could help me to replicate the issue.

**Comment by Rajala1404** [comment]
The thing you're pinging is the service provider and not the actual proxy. If it helps, the full proxy address is:

**Comment by Rajala1404** [comment]
Good news (maybe) it's not the Proxy that caused the Exception it also get this Exception on normal WiFi so maybe my build was broken

**Comment by Rajala1404** [comment]
So i reinstalled the App with your APK and the fetching of the Schools works just fine, but the actual Login always Fails (regardless of School WiFi or not) with Unbekannter Fehler (Unknown Error)

**Comment by alessioC42** [comment]
That's at least something! I cannot think of anything that would be different with the requests. The vpn may help me replicateing this issue.

**Comment by Rajala1404** [comment]
I can't create a VPN (at least with my knowledge) behind our organization network. I will still try it, but for now, I try to fix this issue myself with an Pull Request

**Pull request closed without merging**
